title: Halvkyrie's Page
description:
theme: jekyll-theme-cayman
permalink: pretty
debug:
  show_page_path: false
header:
  buttons:
    - index
    - posts
    - categories
    - about
show_downloads: false
collections: 
  games:
    output: true
    permalink: /:collection/:path
page_index:
  hide_main: true